version: '3.4'
services:
  devserver:
    container_name: mindfield_dev_server
    build:
      context: ./
    command: ["npm", "run", "serve"]
    working_dir: /tmp/
    environment:
      VUE_APP_VERSION: ${VUE_APP_VERSION}
      VUE_APP_ENV: ${VUE_APP_ENV}
      VUE_APP_FIREBASE_API_KEY: ${VUE_APP_FIREBASE_API_KEY}
      VUE_APP_FIREBASE_AUTH_DOMAIN: ${VUE_APP_FIREBASE_AUTH_DOMAIN}
      VUE_APP_FIREBASE_DATABASE_URL: ${VUE_APP_FIREBASE_DATABASE_URL}
      VUE_APP_FIREBASE_PROJECT_ID: ${VUE_APP_FIREBASE_PROJECT_ID}
      VUE_APP_FIREBASE_STORAGE_BUCKET: ${VUE_APP_FIREBASE_STORAGE_BUCKET}
      VUE_APP_FIREBASE_MESSAGING_SENDER_ID: ${VUE_APP_FIREBASE_MESSAGING_SENDER_ID}
      VUE_APP_FIREBASE_APP_ID: ${VUE_APP_FIREBASE_APP_ID}
      FIREBASE_AUTH_EMULATOR_HOST: ${FIREBASE_AUTH_EMULATOR_HOST}
      FIRESTORE_EMULATOR_HOST: ${FIRESTORE_EMULATOR_HOST}
      GCLOUD_PROJECT: ${GCLOUD_PROJECT}
    ports:
      - "80:80"
      - "4000:4000"
      - "4400:4400"
      - "4500:4450"
      - "5001:5001"
      - "8000:8000"
      - "8080:8080"
      - "9099:9099"
 
    volumes:
        - type: bind
          source: ./
          target: /tmp
    networks:
      - mindfield

networks:
  mindfield:
    driver: bridge
